services:
  db:
    image: postgres:16.2
    restart: always
    ports:
      - "0.0.0.0:5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: database_sqlx
    volumes:
      - ./postgres:/var/lib/postgresql/data
